[package]
name = "domain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.58"
nanoid = "0.4.0"


[dev-dependencies]
tokio = { version = "1.20.0", features = ["macros", "rt"] }
